[package]
name = "resolution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"

error.workspace = true
parser.workspace = true
common.workspace = true
